# JIRA CONSTANTS

# Jira API URL
JIRA_API_PATH = '/rest/api/2'



# BBUCKET CONSTANTS

# BBucket API URL
BBUCKET_API_PATH = '/rest/api/1.0'
BBUCKET_BUILD_API_PATH = '/rest/build-status/1.0'
BBUCKET_PERM_API_PATH = '/rest/branch-permissions/2.0'

# BBUCKET permissions
BBUCKET_PERM_READONLY = 'read-only'
BBUCKET_PERM_PULLREQUESTONLY = 'pull-request-only'
BBUCKET_PERM_FASTFORWARDONLY = 'fast-forward-only'
BBUCKET_PERM_NODELETES = 'no-deletes'

BBUCKET_MATCHERTYPE_BRANCH = 'BRANCH'
BBUCKET_MATCHERTYPE_PATTERN = 'PATTERN'
